version: "3.8"

services:
  api:
    build: .
    volumes:
      - .:/app
      - ./app/db-data
    ports:
      - 4080:80
    depends_on: 
      - db

  db:
    image: timescale/timescaledb:1.7.0-pg12
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: uloom
      POSTGRES_PASSWORD: uloompassword
